Muebles.MVC/Models/OrderProductViewModel.cs
using Muebles.CORE;
using System.ComponentModel.DataAnnotations;

namespace Muebles.MVC.Models
{
    /// <summary>
    /// Clase modelo de líneas de pedido
    /// </summary
    public partial class OrderProductViewModel
    {
        /// <summary>
        /// Identificador
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Id del producto
        /// </summary>
        public int ProductId { get; set; }

        /// <summary>
        ///  Nombre del producto
        /// </summary>
        public string ProductName { get; set; }

        /// <summary>
        ///  Precio unitario"
        /// </summary>
        public float ProductPrice { get; set; }

        /// <summary>
        /// Cantidad
        /// </summary>
        public int Number { get; set; }

        /// <summary>
        /// Precio
        /// </summary>
        public float Price { get; set; }

    }
}

Muebles.MVC/Controllers/OrderProductController.cs
using Muebles.Application;
using System;
using System.Collections.Generic;
using System.Linq;
using Muebles.CORE;
using System.Web.Mvc;
using Muebles.MVC.Models;
using Muebles.IFR;

namespace Muebles.MVC.Controllers
{
    /// <summary>
    /// Clase de gestión de líneas de pedidos
    /// </summary>
    public class OrderProductController : Controller
    {

        readonly IOrderProductManager orderProductManager;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="tempOrderProduct">manager</param>
        public OrderProductController(IOrderProductManager tempOrderProduct)
        {
            this.orderProductManager = tempOrderProduct;
        }

        public OrderProductController() { }

        /// <summary>
        /// Método para mostrar todas las líneas del pedido cuyo id coincide con el pasado por parámetro
        /// <param name="id">Id del pedido</param>
        /// <returns>Resultado de la acción</returns>
        /// </summary>
        public ActionResult Index(int idPedido)
        {

            DAL.ApplicationDbContext context = new DAL.ApplicationDbContext();
            ProductManager productManager = new ProductManager(context);

            try
            {
                List<OrderProduct> lista = orderProductManager.GetOPByOrderId(idPedido).ToList(); //Obtenemos la lista de las líneas del pedido con el id pasado por parémtro
                if (lista.Count != 0)
                {
                    //Creamos un modelo de vista con los datos de las líneas del pedido
                    var lineas = lista.Select(i => new OrderProductViewModel()
                    {
                        Id = i.Id,
                        ProductId = i.ProductId,
                        ProductName = productManager.GetById(i.ProductId).Name, //Nombre del producto
                        ProductPrice = productManager.GetById(i.ProductId).Price, //Precio unitario del producto
                        Number = i.Number,
                        Price = productManager.GetById(i.ProductId).Price * i.Number //Precio
                    });
                    return View(lineas); //devolvemos el modelo de vista
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                //Guardamos información de la excepción en el archivo de log
                Log.LogError(ex.Message, ex);
                return View();
            }
        }

        /// <summary>
        /// Método para mostrar el formulario de creación de línea de pedido
        /// <returns>Resultado de la acción</returns>
        /// </summary>
        public ActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Método para guardar la nueva línea de pedido
        /// <param name="i">Modelo de la vista de la línea de pedido</param>
        /// <param name="id">Id del pedido</param>
        /// <returns>Resultado de la acción</returns>
        /// </summary>
        [HttpPost]
        public ActionResult Create(OrderProductViewModel i, int idPedido)
        {

            float total = (float)0.0; //total del pedido
            float price = (float)0.0; //precio de la línea de pedido

            try
            {
                
                DAL.ApplicationDbContext context = new DAL.ApplicationDbContext();
              
                //Creamos una nueva línea de pedido
                OrderProduct or = new OrderProduct()
                {
                    Id = i.Id,
                    OrderId = idPedido,
                    ProductId = i.ProductId,
                    Number = i.Number

                };
                //Añadimos la línea de pedido al contexto de datos
                orderProductManager.Add(or);
                context.SaveChanges();

                OrderManager orderManager = new OrderManager(context);
                Order pedido = orderManager.GetById(idPedido); //Obtenemos el pedido con el id pasado por parámetro

                ProductManager productManager = new ProductManager(context);
                Product producto = new Product();

                List<OrderProduct> listaOP = new List<OrderProduct>();
                listaOP = orderProductManager.GetOPByOrderId(pedido.Id).ToList(); //obtenemos la lista de las líneas del pedido

                //Recorremos la lista y actualizamos el total del pedido
                foreach (OrderProduct op in listaOP)
                {
                    producto = productManager.GetById(i.ProductId);
                    price = producto.Price * op.Number;
                    total += price;  
                }

                pedido.Total = total; //asignamos el total a pagar al pedido
                context.SaveChanges(); //Guardamos los cambios

                return RedirectToAction("Index", new { idPedido = pedido.Id }); //Abrimos la página de la lista de líneas de pedido
            }
            catch (Exception ex)
            {
                //Guardamos información de la excepción en el archivo de log
                Log.LogError(ex.Message, ex);
                return View();
            }
        }

        /// <summary>
        /// Método para mostrar los detalles de la línea de pedido que se desea modificar
        /// <param name="id">Id de la línea de pedido a modificar</param>
        /// <returns>Resultado de la acción</returns>
        /// </summary>
        public ActionResult Edit(int id)
        {
            DAL.ApplicationDbContext context = new DAL.ApplicationDbContext(); //contexto de datos
            
            try
            {
                ProductManager productManager = new ProductManager(context);
                OrderProduct i = orderProductManager.GetById(id); //Obtenemos la línea de pedido con el id pasado por parámetro
                if (i != null)
                {
                    //Creamos un modelo de vista con los datos de la línea del pedido
                    OrderProductViewModel vm = new OrderProductViewModel()
                    {
                        ProductId = i.ProductId,
                        ProductName = productManager.GetById(i.ProductId).Name,
                        Number = i.Number,

                    };
                    return View(vm); //devolvemos el modelo de vista
                }
                else
                {
                    //Si la línea de pedido no existe, abrimos la página de creación de una nueva línea de pedido
                    return RedirectToAction("Create");
                }
            }
            catch (Exception ex)
            {
                //Guardamos información de la excepción en el archivo de log
                Log.LogError(ex.Message, ex);
                return View();
            }
        }

        /// <summary>
        /// Método para guardar los cambios en los datos de la línea de pedido
        /// <param name="id">Id de la línea de pedido</param>
        /// <param name="i">Modelo de la vista de datos de la línea de pedido</param>
        /// <returns>Resultado de la acción</returns>
        /// </summary>
        [HttpPost]
        public ActionResult Edit(int id, OrderProductViewModel i)
        {

            #region Inicialización de las variables
            float total = (float)0.0;
            float price = (float)0.0;
            Product producto = new Product();
            List<OrderProduct> listaOP = new List<OrderProduct>();
            DAL.ApplicationDbContext context = new DAL.ApplicationDbContext();
            #endregion

            try
            {
                
                ProductManager productManager = new ProductManager(context); //manager de productos

                OrderProduct p = orderProductManager.GetById(id); //obtenemos la línea de pedido con el id pasado por parámetro
                //actualizamos sus valores
                p.Id = i.Id;
                p.ProductId = i.ProductId;
                p.Number = i.Number;

                OrderManager orderManager = new OrderManager(context);
                Order pedido = orderManager.GetById(p.OrderId);  //Obtenemos el pedido al que pertenece la línea de pedido


                listaOP = orderProductManager.GetOPByOrderId(pedido.Id).ToList(); //obtenemos la lista de las líneas del pedido
                if (listaOP.Count != 0)
                {
                    //si no está vacía, la recorremos para actualizr el total del pedido
                    foreach (OrderProduct op in listaOP) 
                    {
                        producto = productManager.GetById(i.ProductId);
                        price = producto.Price * op.Number;
                        total += price; //calculamos el total del pedido
                    }
                }

                //asignamos suma total a pagar al pedido y guardamos los cambios
                pedido.Total = total;
                context.SaveChanges();

                return RedirectToAction("Index", new { idPedido = pedido.Id }); //Abrimos la página de la lista de líneas de pedido
            }
            catch (Exception ex)
            {
                //Guardamos información de la excepción en el archivo de log
                Log.LogError(ex.Message, ex);
                return View();
            }
        }


        /// <summary>
        /// Método que elimina una línea de pedido del pedido
        /// </summary>
        /// <param name="id">Id de la línea de pedido</param>
        /// <returns>Resultado de la acción</returns>
        public ActionResult DeleteItem(int id)
        {
            try
            {

                DAL.ApplicationDbContext context = new DAL.ApplicationDbContext(); //contexto de datos
                OrderProduct item = orderProductManager.GetById(id); //Obtenemos la llínea de pedido a partir de su id

Muebles.MVC/Views/OrderProduct/Create.cshtml
@model Muebles.MVC.Models.OrderProductViewModel

@{
    ViewBag.Title = "Create";
}

<div style="margin-top:10px;margin-bottom:10px">
    <div class="page-header"><h1 style="color: #591d1d">Añadir producto al pedido</h1></div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>


        <div>
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Añadir" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Muebles.MVC/Views/OrderProduct/Delete.cshtml
@model Muebles.MVC.Models.OrderProductViewModel

@{
    ViewBag.Title = "Delete";
}

<div style="margin-top:10px;margin-bottom:10px">
    <div class="page-header"><h2 style="color: #591d1d">Eliminar producto del pedido</h2></div>
</div>

<h3>¿Está seguro de que desea eliminar el producto del pedido?</h3>
<div>

  
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" />

        </div>
    }
</div>

Muebles.MVC/Views/OrderProduct/Edit.cshtml
@model Muebles.MVC.Models.OrderProductViewModel

@{
    ViewBag.Title = "Edit";
}


<div style="margin-top:10px;margin-bottom:10px">
    <div class="page-header"><h1 style="color: #591d1d">Modificación</h1></div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
  
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al pedido", "Index", "OrderProduct", new { idPedido = Model.Id }, null)
</div>

Muebles.MVC/Views/OrderProduct/Index.cshtml
@model IEnumerable<Muebles.MVC.Models.OrderProductViewModel>

@{
    ViewBag.Title = "Index";
}

<div style="margin-top:10px;margin-bottom:20px">
    <h1 style="color: #591d1d">Pedido</h1>

    @if (TempData["Success"] != null)
            {
        <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
    }
</div>

<table class="table table-responsive table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProductPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Number)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.ActionLink("Modificar", "Edit", new { id = item.Id }, new { @style = "color: #591d1d" }) |
                    @Html.ActionLink("Eliminar", "DeleteItem", new { id = item.Id }, new { @style = "color: #591d1d" })

                </td>
            </tr>
        }
    }


</table>

<p>
    @Html.ActionLink("Volver", "Index", "Order", null, new { @class = "btn btn-md btn-default" })
</p>